name: Build Wheels with cibuildwheel

on:
  workflow_dispatch:

jobs:
  build_macos_wheels:
    name: Build macOS wheels
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # Build only CPython 3.11 wheels
          CIBW_BUILD: "cp311-*"
          CIBW_SKIP: "cp38-* cp39-* cp310-* cp312-* cp313-* cp314-*"

          # Build both Intel + Apple Silicon wheels (separate, not universal2)
          CIBW_ARCHS_MACOS: "x86_64 arm64"

          # Per-wheel build setup
          CIBW_BEFORE_BUILD: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install meson-python

          # Verbose logs
          CIBW_BUILD_VERBOSITY: "1"

          # Simple import
          CIBW_TEST_COMMAND: |
            python -c "import retracesoftware.stableset; print('✅ Import successful!')"
            python -c "import retracesoftware.stableset as stableset; s = stableset.set([1, 2, 3]); print('✅ Test passed:', len(s))"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: wheelhouse/*.whl
          retention-days: 30
